title: <p align="center"> Krishna Prasad Varma </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/krishnaprasadvarma">LinkedIn</a> |
  <a href="https://github.com/kpvarma27">GitHub</a>
  
  <br>
  Programmer, primarily working on Ruby, NodeJs and Python. Tried GoLang in between and recently learning Data Science.
  <br>
  </p>



theme: jekyll-theme-minimal
